entities:
  university_of_california:
    channel_ids:
      - '609c2f4dca30db000bfb36f7'
    config:
      - name: "Campus"
        type: "select"
        options:
          - "UC Irvine"
          - "UC Santa Barbara"
          - "UC Davis"
          - "UC Berkeley"
      - name: "Program of Interest"
        type: "select"
        options:
          - "Bachelor's of Science"
          - "Masters in Information Systems"
          - "Masters in Finance"
          - "Masters in Accounting"
      - name: "Notes"
        type: "textarea"

  claremont_university:
    channel_ids:
      - '60a77a810880e9000cac65ac'
    config:
      - name: "Where did you hear about us"
        type: "select"
        options:
          - "Informational Session"
          - "Internet"
          - "Referral"
      - name: "Address"
        type: "input"
